name: SwiftUIPractice
options:
  bundleIdPrefix: com.robert.gravina  
packages:
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector
    from: 0.9.11
  Nimble:
    url: https://github.com/Quick/Nimble
    from: 13.3.0
targets:
  SwiftUIPractice:
    type: application
    platform: iOS
    deploymentTarget: "17.4"
    sources:
      - SwiftUIPractice
    info:
      path: SwiftUIPractice/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: true
    scheme:
      testTargets:
      - SwiftUIPracticeTests
  SwiftUIPracticeTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: SwiftUIPractice
      - package: ViewInspector
      - package: Nimble
    module: SwiftUIPractice
    sources:
      - SwiftUIPracticeTests
    info:
      path: SwiftUIPracticeTests/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen