name: SwiftUIPractice
options:
  bundleIdPrefix: com.robert.gravina  
targets:
  SwiftUIPractice:
    type: application
    platform: iOS
    deploymentTarget: "17.4"
    sources:
      - SwiftUIPractice
    info:
      path: SwiftUIPractice/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    scheme:
      testTargets:
      - SwiftUIPracticeTests
  SwiftUIPracticeTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: SwiftUIPractice
    module: SwiftUIPractice
    sources:
      - SwiftUIPracticeTests
    info:
      path: SwiftUIPracticeTests/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen